### ISSUE TITLE
Reuses the deleted row which makes the new row in editing mode

### ISSUE THREAD

**Issue by hgopinath** [Shopify/FunctionalTableData#70]
**Issue:**
When there are multiple rows in a section and when I try to delete a row, it reuses the deleted row for the immediate row which shouldn't. This makes the row below the deleted row to be in editing mode.

https://github.com/Shopify/FunctionalTableData/blob/d347cccad3ef2bcc2ea9abac2ced7410203a1a56/FunctionalTableData/TableView/FunctionalTableData.swift#L385-L387

Adding `tableView.setEditing(false)` when deleting the rows in the snippet fixes the issue. But that wouldn't be an appropriate solution. So we might need to look into a better solution.

![functionaltable](https://user-images.githubusercontent.com/35339464/35999521-1e2e8b98-0cee-11e8-82f8-f612e612ca56.gif)

**Comment by raulriera** [comment]
The GIF seems to be deleting other rows as well, not the ones you are actually clicking

**Comment by hgopinath** [comment]
Its actually deleting the intended row. But the animation makes it look like the other row is been deleted.

**Comment by raulriera** [comment]
Check that your identifiers for the cells are not numbers but actual identifiable data for the rows... If you use numbers 1,2,3 for example and delete 2. FTD will think that the last one was deleted and removed it with animation (as the example in your gif) because now the remaining keys are 1 and 2. Yet the data is updated correctly encase the cells gets reused and you are applied the data again in the cellUpdater.

```swift
return LabelCell(
				key: "id-\(index)", // this would be a bad example of a key, and sadly is in the playground
				actions: actions,
				state: LabelState(text: item),
				cellUpdater: LabelState.updateView)
```

**Comment by hgopinath** [comment]
Identifiers with row indices was the issue. Changing that seems to fix it.
